/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public static void main(String[] args) {
        Game.Config config = new Game.Config(
            10,
            10,
            10,
            10,
            10
        );

        Game game = new Game(config);
        game.simulate();
    }
}
