/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import game.statistics.Statistics;

public class App {
    public static void main(String[] args) throws Exception {
        new Statistics();
    }
}
